// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4z8aqxHXkX3MUWICtEx88XeQgynmPGOQ',
    appId: '1:741814478457:web:2cb23aba11baf3a21bd6a8',
    messagingSenderId: '741814478457',
    projectId: 'portfoliowebsite-36391',
    authDomain: 'portfoliowebsite-36391.firebaseapp.com',
    storageBucket: 'portfoliowebsite-36391.appspot.com',
    measurementId: 'G-DVPJWB4DF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3lizLIdJxzGc_8yG3jDLwg4pJS-DGk3E',
    appId: '1:741814478457:android:76331e9970f1c2f61bd6a8',
    messagingSenderId: '741814478457',
    projectId: 'portfoliowebsite-36391',
    storageBucket: 'portfoliowebsite-36391.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANdNw8NBtWuTRGZGHxJRV17PsAzH8EyfE',
    appId: '1:741814478457:ios:383c7c5b8b0a92961bd6a8',
    messagingSenderId: '741814478457',
    projectId: 'portfoliowebsite-36391',
    storageBucket: 'portfoliowebsite-36391.appspot.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANdNw8NBtWuTRGZGHxJRV17PsAzH8EyfE',
    appId: '1:741814478457:ios:383c7c5b8b0a92961bd6a8',
    messagingSenderId: '741814478457',
    projectId: 'portfoliowebsite-36391',
    storageBucket: 'portfoliowebsite-36391.appspot.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4z8aqxHXkX3MUWICtEx88XeQgynmPGOQ',
    appId: '1:741814478457:web:113c486180da3fff1bd6a8',
    messagingSenderId: '741814478457',
    projectId: 'portfoliowebsite-36391',
    authDomain: 'portfoliowebsite-36391.firebaseapp.com',
    storageBucket: 'portfoliowebsite-36391.appspot.com',
    measurementId: 'G-DTE9WDG4JX',
  );
}
